### PR TITLE
feat(jest): update json schema for reporters (#1343)

### PR DESCRIPTION
**Pull request by csnate**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

I didn't see of a way to test the schema and there are no docs on the schema either.

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1343 

## What is the new behavior?

Corrects the schema.json

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by csnate** [comment]
@just-jeb I'm trying to run the tests locally like so:

```
$ cd packages/jest
$ ./scripts/ci.sh
```

But I'm getting the following error:

`Error: Could not find the '@angular-builders/jest:run' builder's node package.`

I've ran `yarn install` from the root, and from the `packages/jest`, `examples/jest/simple-app`, and `examples/jest/multiple-apps` directories but still hitting that error. Is there any documentation to follow about how to run the tests locally or any idea what that error means?

Unrelated - I don't think this is related to this branch, but check the [build results](https://github.com/just-jeb/angular-builders/actions/runs/4407324552/jobs/7739119261). There are a number of warnings/errors in the `[@angular-builders/custom-webpack]` tests that look like there could be a missing type in a tsconfig somewhere - `Property 'toEqual' does not exist on type 'Assertion'. Did you mean 'equal'?`

**Comment by just-jeb** [comment]
Yeah, sorry about that, no docs for contribution, I really should do that just not getting there. 
So in order to be able to run the CI scripts you need to run `yarn` and `yarn build:packages` from the root. 
An alternative is to run `yarn` and then `yarn ci` from root (this will also run CI script for other builders though). You kinda can get a sense of what's going on from [here](https://github.com/just-jeb/angular-builders/blob/master/.github/workflows/ci.yml). After every schema change you need to run `yarn build` in `jest` folder again. 

And yeah, I totally need to move these horrible shell scripts to node 😅.  

Regarding the build, the warnings you see are not related and you can ignore them, they are not failing the build. 
The culprit is at the end: 
```
➤ YN0000: [@angular-builders/jest]: Process started
➤ YN0000: [@angular-builders/jest]: Error: `type` must contain only strings, but it has [object Object].
➤ YN0000: [@angular-builders/jest]: Process exited (exit code 1), completed in 4s 211ms
```

Seems like an issue with the schema definition.   

Let me know if you need any further assistance 🙏.

**Comment by csnate** [comment]
@just-jeb - got the tests running locally and fixed the issue. Also added an e2e test for reporters. Let me know if that's what you were thinking or if you just wanted me to add the `reporters`/`coverageReporters` options to an existing e2e test.

NOTE - when running `./scripts/ci.sh` I see the following error at the end:

```
./scripts/ci.sh: line 50: local: -n: invalid option
local: usage: local name[=value] ...
ERROR: ./scripts/ci.sh:48 local -n testOptions=$2
```

Happens in the master branch as well

**Comment by csnate** [comment]
Nm about the `local` error - that looks like a "me" issue running MacOS

**Comment by csnate** [comment]
@just-jeb - yep, all of that makes sense. I'll make the changes. 

And yea, I saw that `Error: Unknown argument: reporters` error as well and started looking into why that is failing, but when running just that specific test locally (`yarn test --reporters=default --reporters=jest-junit`) it passes for me. I'll continue to investigate

**Pull request closed without merging**
