### PR TITLE
chore(deps)!: update to angular 12

### PR DESCRIPTION
**Pull request by sonallux**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other... Please describe: Update to angular 12
```

## What is the current behavior?

Angular 12 is not supported

Issue Number: #972

## What is the new behavior?

- Updated all angular dependencies to Angular 12
- Updated examples to Angular 12
- Bump minimum supported NodeJS version to 12.14.0 because Angular 12 no longer supported NodeJS 10
- Update `html-webpack-plugin` in example, because the current version is not compatible with webpack 5

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

### CODE REVIEW

**Comment by rudivanbiljon** [comment]
Webpack should probably be updated too?

**Comment by sonallux** [comment]
> Webpack should probably be updated too?

Webpack is already updated because the dependency to Webpack 5 is contained in the angular package.

**Review by rudivanbiljon — APPROVED** [review]
Looks good, hoping this can be merged soon

**Review by just-jeb — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by just-jeb** [comment]
@all-contributors please add @sonallux for code

**Pull request merged**
