### PR TITLE
chore(deps)!: update to Angular 16

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by jornare** [comment]
looks like tsconfig needs to allow plain js to get the CI to proceed.

**Comment by kaysaith1900** [comment]
Hurry up and combine it, use it in a hurry

**Comment by Nicoss54** [comment]
@arturovt is this Pull request can be change to stable status ? Now the CI seems passing :) 
Thanks for the woek you did 👍  !

**Comment by MaximSagan** [comment]
@just-jeb Can we get this one merged?

**Review by just-jeb — APPROVED** [review]
README.MDs should be updated with proper versions/pre-requisites, otherwise LGTM. Merging in order to allow people move forward with the beta version, let's make another patch PR for the docs.

**Pull request merged**
