### PR TITLE
feat: add @bazel/angular package

### PR DESCRIPTION
**Pull request by alexeagle**
This provides a very small shim builder, which spawns the Bazel build tool under an ng build or ng test command.
It can be useful during a migration, where developers use Angular CLI but some parts of the workspace build and test with Bazel.

It is moving from https://github.com/bazelbuild/rules_nodejs/tree/stable/packages/angular
because that project is cutting scope.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

Feature

## What is the current behavior?

Issue Number: #1047 

## What is the new behavior?

See added README

## Does this PR introduce a breaking change?

No

### CODE REVIEW

**Comment by just-jeb** [comment]
Hey @alexeagle, I'll do the upgrade, no problem.   
Are there any tests (e2e o UT) that can be added? Any open issues that should be moved here as well?

**Comment by just-jeb** [comment]
@alexeagle Another question, would it be OK to move it under `@angular-builders` scope? Like `@angular-builders/bazel`?

**Comment by just-jeb** [comment]
Also, can I have write access to the repo so that I could push to this PR please?

**Comment by alexeagle** [comment]
Sure, I invited you to that repo with write access. I'm surprised my usual GitHub settings for "Allow edits by project maintainers" didn't apply here to give you push access to that branch automatically.

Nope no open issues for this code, and also no automated tests. It's a very simple bit of glue, which hasn't changed since we added it. Also, since it doesn't have any conditional logic, it's not very unit-testable. I could imagine an integration test if that's important to you.

**Comment by just-jeb** [comment]
Well I was thinking about a simple Angular app (even the auto generated one) with Bazel config that uses this builder, just to have a regression test and make sure I'm not breaking anything.
Alas I don't have much experience with Bazel, so if you just added such an app here (under examples directory, just like the other builders) or alternatively pointed me out to an example that I can copy, this would be great.

**Comment by alexeagle** [comment]
Here's an old example that uses this builder
https://github.com/angular/angular-bazel-example/blob/master/angular.json

Note that to test this, there's no need to even have an angular app. We just want to run `ng build` and have bazel perform some simple action like write a file containing "hello world" or something.

**Comment by alexeagle** [comment]
I added a commit with a bit of bare files. Didn't try adding a package.json in there yet - I'm not sure how much fixture is required to make your monorepo e2e test runner work here.

**Comment by alan-agius4** [comment]
Thanks @just-jeb for accepting to add this in your repo and thanks @alexeagle for porting this. 

If anyone needs helps feel free to reach out 😁

**Comment by just-jeb** [comment]
@all-contributors please add @alexeagle and @alan-agius4 for code.

**Comment by just-jeb** [comment]
@all-contributors please add @alan-agius4 for code.

**Comment by Mawi137** [comment]
@ngx-translate released an update today to support Angular 13, however in my jest tests I keep getting this error:
```
C:\dev\prj\Angular13Test\node_modules\@ngx-translate\core\fesm2015\ngx-translate-core.mjs:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as i0 from '@angular/core';
                                                                                                                                           ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Component } from '@angular/core';
    > 2 | import {TranslateService} from '@ngx-translate/core';
        | ^
      3 |
      4 | @Component({
      5 |   selector: 'app-root',

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/app/app.component.ts:2:1)
```
Any idea what the issue might be? I also started from a new Angular project and added ngx-translate + jest. It has this issue as well.

**Comment by just-jeb** [comment]
@Mawi137 Hey, I'm sorry, how is that related to `@angular-builders` in general and to `@angular-builders/bazel` in particular?

**Comment by Mawi137** [comment]
Ah sorry, must have thought that this was the Angular 13 issue 😅

**Pull request merged**
