### PR TITLE
feat(custom-webpack): export common

### PR DESCRIPTION
**Pull request by IKatsuba**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

I need to use only the factory for modification of `webpack` configuration. But the factory is not exported.

Issue Number: N/A

## What is the new behavior?

The factory is exported

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by just-jeb** [comment]
Hi @IKatsuba. Would you mind elaborating on your use case. Everything that is exported is part of the public API and should be documented. How do you plan to use it?

**Comment by IKatsuba** [comment]
Hi @just-jeb. I am creating a builder with built-in index.html transform factories and really want to reuse webpack configuration transform factory from your package

**Comment by just-jeb** [comment]
Ok. For now I'll merge it as is but maybe it's worth externalizing all the core functionality into a separate package, WDYT?

**Comment by IKatsuba** [comment]
That would be very useful!

**Pull request merged**
