### PR TITLE
build: update jest-preset-angular

### PR DESCRIPTION
**Pull request by matheo**
I'd like to request the official `@angular-builders/jest@13.0.4` release.
Thanks in advance!

## PR Type

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by just-jeb** [comment]
Just to be clear - you want `jest-preset-angular` to be updated to `11.1.2`?

**Comment by KyDenZ** [comment]
`jest-preset-angular@12.0.0` is published

**Comment by just-jeb** [comment]
I see there is a lot of breaking changes. I think the right timing would be to update the version along with Angular major release (`@angular-builders/jest@14`), which, judging by their [releases](https://github.com/angular/angular/releases) should happen pretty soon. I'll add an issue for this.

**Comment by just-jeb** [comment]
https://github.com/just-jeb/angular-builders/issues/1205

**Comment by matheo** [comment]
@just-jeb this had no breaking changes, and also syncs the dev-dependencies in this monorepo which is not trivial :thinking:

**Comment by just-jeb** [comment]
@matheo that's why I asked what was the intention of this PR.  
`jest-preset-angular@11.1.2` is [merged](https://github.com/just-jeb/angular-builders/pull/1207) to master.

**Pull request closed without merging**
