### PR TITLE
fix(custom-webpack): specify possible types of customWebpackConfig values

### PR DESCRIPTION
**Pull request by juristr**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

At the moment if someone uses this with the latest versions of [Nx](https://nx.dev) and does not specify a `webpack.config.js` the build fails because it requires one.

The reason is how the defaults are being interpreted by the Angular CLI vs Nx schema parser. Right now the `custom-webpack` browser schema defines `customWebpackConfig` to be of type `object` but assigns a boolean value as the default. The Angular CLI is less strict in that it accepts that, while Nx is more strict (I'm working on the Nx side to avoid such edge cases as much as possible).

## What is the new behavior?

This PR adjusts the schema to properly reflect the possible types, basically a `object` or `boolean`. This is achieved with the `oneOf` property in the schema file.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by just-jeb** [comment]
I think the default value `false` is a leftover from the very early days of the builder.  
The right type would be then `object` or `undefined` with no default value (this should fix the problem with `Nx` as well).

**Comment by juristr** [comment]
@just-jeb passing undefined/null or no default value wouldn't work as the Angular CLI (and Nx) initialize those values with a default object.

image

Thus the check in the `CustomWebpackBuilder` fails and would require the user to specify a custom webpack configuration.

I don't think using `false` as the default value is wrong at all, it's just the schema that needs to be adjusted to account for that. Very similar to what the Angular devkit builder does for the `optimization` property. Let me know what you think

**Comment by juristr** [comment]
@just-jeb Sorry for pinging 😅. Any opinion on the above?

**Comment by just-jeb** [comment]
Sounds good to me

**Review by just-jeb — APPROVED** [review]

**Comment by just-jeb** [comment]
@all-contributors please add @juristr for code

**Pull request merged**
